project:
  type: website
  output-dir: docs

website:
  title: "The International Civil Service Effectiveness Project"
  navbar:
    title: "The InCiSE Project"
    background: dark
    right:
      - text: "InCiSE 2024"
        href: incise2024.qmd
      - text: "InCiSE 2019"
        menu:
          - text: "Read the InCiSE 2019 Results Report"
            icon: book-half
            href: https://incise-project.github.io/incise2019-results/
          - text: "View the InCiSE 2019 Results Dashboard"
            icon: bar-chart-fill
            href: https://incise-project.github.io/incise2019-dashboard/
          - text: "Read the InCiSE 2019 Technical Report"
            icon: book-half
            href: https://incise-project.github.io/incise2019-techreport/
  page-footer:
    left: "Copyright Blavatnik School of Government"

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - custom.scss
    anchor-sections: false
